version: '3.6'

x-quorum-def:
  &quorum-def
  restart: "always"
  image: quorumengineering/quorum:latest
  expose:
    - "21000"
    - "50400"
    - "8545"
    - "8546"
    - "8547"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      # Initialize genesis block if not already initialized
      if [ ! -d "/qdata/dd/geth/chaindata" ]; then
        echo "Initializing genesis block..."
        geth --datadir /qdata/dd init /qdata/dd/genesis.json
      fi
      
      # Start Quorum without private transaction support to save resources
      echo "Starting Quorum without private transaction support..."
      PRIVATE_CONFIG=ignore geth --datadir /qdata/dd \
        --nodiscover \
        --allow-insecure-unlock \
        --verbosity 3 \
        --istanbul.blockperiod 5 \
        --syncmode full \
        --mine \
        --miner.threads 1 \
        --http \
        --http.corsdomain "*" \
        --http.vhosts "*" \
        --http.addr 0.0.0.0 \
        --http.port 8545 \
        --http.api admin,eth,debug,miner,net,txpool,personal,web3,istanbul \
        --port 21000 \
        --unlock 0 \
        --password /qdata/passwords.txt

services:
  node-0:
    << : *quorum-def
    hostname: node-0
    ports:
      - "0.0.0.0:22000:8545"  # Expose RPC to all interfaces
      - "0.0.0.0:21000:21000"  # Expose P2P to all interfaces
    volumes:
      - ./qdata/node-0:/qdata

  node-1:
    << : *quorum-def
    hostname: node-1
    ports:
      - "127.0.0.1:22001:8545"  # Only expose locally
      - "127.0.0.1:21001:21000"  # Only expose locally
    volumes:
      - ./qdata/node-1:/qdata

  node-2:
    << : *quorum-def
    hostname: node-2
    ports:
      - "127.0.0.1:22002:8545"  # Only expose locally
      - "127.0.0.1:21002:21000"  # Only expose locally
    volumes:
      - ./qdata/node-2:/qdata

  node-3:
    << : *quorum-def
    hostname: node-3
    ports:
      - "127.0.0.1:22003:8545"  # Only expose locally
      - "127.0.0.1:21003:21000"  # Only expose locally
    volumes:
      - ./qdata/node-3:/qdata

  node-4:
    << : *quorum-def
    hostname: node-4
    ports:
      - "127.0.0.1:22004:8545"  # Only expose locally
      - "127.0.0.1:21004:21000"  # Only expose locally
    volumes:
      - ./qdata/node-4:/qdata
